library(arules)
library(arulesViz)
library(datasets)
data("Groceries")
itemFrequencyPlot(Groceries,topN=20,type="absolute")
rules<-apriori(Groceries,parameter = list(sup=0.001, conf= 0.8))
inspect(head(rules))
rules<-sort(rules,by="confidence",decreasing = TRUE)
inspect(head(rules))